name: Backend CI (Integración Continua)

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping:1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Instalar uv y habilitar caché
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Configurar Python
      run: uv python install

    - name: Instalar dependencias del proyecto
      run: uv sync --all-extras --dev

    - name: Análisis de Código y Estilo
      run: |
        uv run black --check app/
        uv run flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Pruebas Unitarias
      run: |
        uv run pytest test/unit/ -m "unit" --cov=app --cov-report=term-missing

    - name: Pruebas de Integración
      env:
        CONNECTION_STRING: "mongodb://localhost:27017"
      run: |
        uv run pytest test/integration/ -m "integration" --cov=app --cov-append --cov-report=term-missing --cov-fail-under=80